// Code generated by protoc-gen-go. DO NOT EDIT.
// source: go/src/rpc_blog/proto/blog/blog_ext.proto

package blog_ext

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//LIST
type BlogListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlogListRequest) Reset()         { *m = BlogListRequest{} }
func (m *BlogListRequest) String() string { return proto.CompactTextString(m) }
func (*BlogListRequest) ProtoMessage()    {}
func (*BlogListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0c6db8a9d783a32, []int{0}
}

func (m *BlogListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlogListRequest.Unmarshal(m, b)
}
func (m *BlogListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlogListRequest.Marshal(b, m, deterministic)
}
func (m *BlogListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlogListRequest.Merge(m, src)
}
func (m *BlogListRequest) XXX_Size() int {
	return xxx_messageInfo_BlogListRequest.Size(m)
}
func (m *BlogListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlogListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlogListRequest proto.InternalMessageInfo

type BlogListResponse struct {
	BlogList             []*BlogInfo `protobuf:"bytes,1,rep,name=blogList,proto3" json:"blogList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BlogListResponse) Reset()         { *m = BlogListResponse{} }
func (m *BlogListResponse) String() string { return proto.CompactTextString(m) }
func (*BlogListResponse) ProtoMessage()    {}
func (*BlogListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0c6db8a9d783a32, []int{1}
}

func (m *BlogListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlogListResponse.Unmarshal(m, b)
}
func (m *BlogListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlogListResponse.Marshal(b, m, deterministic)
}
func (m *BlogListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlogListResponse.Merge(m, src)
}
func (m *BlogListResponse) XXX_Size() int {
	return xxx_messageInfo_BlogListResponse.Size(m)
}
func (m *BlogListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlogListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlogListResponse proto.InternalMessageInfo

func (m *BlogListResponse) GetBlogList() []*BlogInfo {
	if m != nil {
		return m.BlogList
	}
	return nil
}

type BlogInfo struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	BuildTime            string   `protobuf:"bytes,2,opt,name=buildTime,proto3" json:"buildTime,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlogInfo) Reset()         { *m = BlogInfo{} }
func (m *BlogInfo) String() string { return proto.CompactTextString(m) }
func (*BlogInfo) ProtoMessage()    {}
func (*BlogInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0c6db8a9d783a32, []int{2}
}

func (m *BlogInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlogInfo.Unmarshal(m, b)
}
func (m *BlogInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlogInfo.Marshal(b, m, deterministic)
}
func (m *BlogInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlogInfo.Merge(m, src)
}
func (m *BlogInfo) XXX_Size() int {
	return xxx_messageInfo_BlogInfo.Size(m)
}
func (m *BlogInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BlogInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BlogInfo proto.InternalMessageInfo

func (m *BlogInfo) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *BlogInfo) GetBuildTime() string {
	if m != nil {
		return m.BuildTime
	}
	return ""
}

func (m *BlogInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

//WRITE
type WriteBlogRequest struct {
	BlogId               string   `protobuf:"bytes,1,opt,name=blogId,proto3" json:"blogId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteBlogRequest) Reset()         { *m = WriteBlogRequest{} }
func (m *WriteBlogRequest) String() string { return proto.CompactTextString(m) }
func (*WriteBlogRequest) ProtoMessage()    {}
func (*WriteBlogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0c6db8a9d783a32, []int{3}
}

func (m *WriteBlogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteBlogRequest.Unmarshal(m, b)
}
func (m *WriteBlogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteBlogRequest.Marshal(b, m, deterministic)
}
func (m *WriteBlogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteBlogRequest.Merge(m, src)
}
func (m *WriteBlogRequest) XXX_Size() int {
	return xxx_messageInfo_WriteBlogRequest.Size(m)
}
func (m *WriteBlogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteBlogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteBlogRequest proto.InternalMessageInfo

func (m *WriteBlogRequest) GetBlogId() string {
	if m != nil {
		return m.BlogId
	}
	return ""
}

type WriteBlogResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteBlogResponse) Reset()         { *m = WriteBlogResponse{} }
func (m *WriteBlogResponse) String() string { return proto.CompactTextString(m) }
func (*WriteBlogResponse) ProtoMessage()    {}
func (*WriteBlogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0c6db8a9d783a32, []int{4}
}

func (m *WriteBlogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteBlogResponse.Unmarshal(m, b)
}
func (m *WriteBlogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteBlogResponse.Marshal(b, m, deterministic)
}
func (m *WriteBlogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteBlogResponse.Merge(m, src)
}
func (m *WriteBlogResponse) XXX_Size() int {
	return xxx_messageInfo_WriteBlogResponse.Size(m)
}
func (m *WriteBlogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteBlogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WriteBlogResponse proto.InternalMessageInfo

func (m *WriteBlogResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *WriteBlogResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

//delete
type DeleteBlogRequest struct {
	BlogId               string   `protobuf:"bytes,1,opt,name=blogId,proto3" json:"blogId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBlogRequest) Reset()         { *m = DeleteBlogRequest{} }
func (m *DeleteBlogRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBlogRequest) ProtoMessage()    {}
func (*DeleteBlogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0c6db8a9d783a32, []int{5}
}

func (m *DeleteBlogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBlogRequest.Unmarshal(m, b)
}
func (m *DeleteBlogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBlogRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBlogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBlogRequest.Merge(m, src)
}
func (m *DeleteBlogRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBlogRequest.Size(m)
}
func (m *DeleteBlogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBlogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBlogRequest proto.InternalMessageInfo

func (m *DeleteBlogRequest) GetBlogId() string {
	if m != nil {
		return m.BlogId
	}
	return ""
}

type DeleteBlogResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBlogResponse) Reset()         { *m = DeleteBlogResponse{} }
func (m *DeleteBlogResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteBlogResponse) ProtoMessage()    {}
func (*DeleteBlogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0c6db8a9d783a32, []int{6}
}

func (m *DeleteBlogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBlogResponse.Unmarshal(m, b)
}
func (m *DeleteBlogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBlogResponse.Marshal(b, m, deterministic)
}
func (m *DeleteBlogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBlogResponse.Merge(m, src)
}
func (m *DeleteBlogResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteBlogResponse.Size(m)
}
func (m *DeleteBlogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBlogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBlogResponse proto.InternalMessageInfo

func (m *DeleteBlogResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DeleteBlogResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

//modify
type ModifyBlogRequest struct {
	BlogId               string   `protobuf:"bytes,1,opt,name=blogId,proto3" json:"blogId,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Detail               string   `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyBlogRequest) Reset()         { *m = ModifyBlogRequest{} }
func (m *ModifyBlogRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyBlogRequest) ProtoMessage()    {}
func (*ModifyBlogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0c6db8a9d783a32, []int{7}
}

func (m *ModifyBlogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyBlogRequest.Unmarshal(m, b)
}
func (m *ModifyBlogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyBlogRequest.Marshal(b, m, deterministic)
}
func (m *ModifyBlogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyBlogRequest.Merge(m, src)
}
func (m *ModifyBlogRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyBlogRequest.Size(m)
}
func (m *ModifyBlogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyBlogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyBlogRequest proto.InternalMessageInfo

func (m *ModifyBlogRequest) GetBlogId() string {
	if m != nil {
		return m.BlogId
	}
	return ""
}

func (m *ModifyBlogRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ModifyBlogRequest) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type ModifyBlogResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyBlogResponse) Reset()         { *m = ModifyBlogResponse{} }
func (m *ModifyBlogResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyBlogResponse) ProtoMessage()    {}
func (*ModifyBlogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0c6db8a9d783a32, []int{8}
}

func (m *ModifyBlogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyBlogResponse.Unmarshal(m, b)
}
func (m *ModifyBlogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyBlogResponse.Marshal(b, m, deterministic)
}
func (m *ModifyBlogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyBlogResponse.Merge(m, src)
}
func (m *ModifyBlogResponse) XXX_Size() int {
	return xxx_messageInfo_ModifyBlogResponse.Size(m)
}
func (m *ModifyBlogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyBlogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyBlogResponse proto.InternalMessageInfo

func (m *ModifyBlogResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ModifyBlogResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

//detail
type BlogDetailRequest struct {
	BlogId               string   `protobuf:"bytes,1,opt,name=blogId,proto3" json:"blogId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlogDetailRequest) Reset()         { *m = BlogDetailRequest{} }
func (m *BlogDetailRequest) String() string { return proto.CompactTextString(m) }
func (*BlogDetailRequest) ProtoMessage()    {}
func (*BlogDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0c6db8a9d783a32, []int{9}
}

func (m *BlogDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlogDetailRequest.Unmarshal(m, b)
}
func (m *BlogDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlogDetailRequest.Marshal(b, m, deterministic)
}
func (m *BlogDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlogDetailRequest.Merge(m, src)
}
func (m *BlogDetailRequest) XXX_Size() int {
	return xxx_messageInfo_BlogDetailRequest.Size(m)
}
func (m *BlogDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlogDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlogDetailRequest proto.InternalMessageInfo

func (m *BlogDetailRequest) GetBlogId() string {
	if m != nil {
		return m.BlogId
	}
	return ""
}

type BlogDetailResponse struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	BuildTime            string   `protobuf:"bytes,2,opt,name=buildTime,proto3" json:"buildTime,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Detail               string   `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlogDetailResponse) Reset()         { *m = BlogDetailResponse{} }
func (m *BlogDetailResponse) String() string { return proto.CompactTextString(m) }
func (*BlogDetailResponse) ProtoMessage()    {}
func (*BlogDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0c6db8a9d783a32, []int{10}
}

func (m *BlogDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlogDetailResponse.Unmarshal(m, b)
}
func (m *BlogDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlogDetailResponse.Marshal(b, m, deterministic)
}
func (m *BlogDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlogDetailResponse.Merge(m, src)
}
func (m *BlogDetailResponse) XXX_Size() int {
	return xxx_messageInfo_BlogDetailResponse.Size(m)
}
func (m *BlogDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlogDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlogDetailResponse proto.InternalMessageInfo

func (m *BlogDetailResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *BlogDetailResponse) GetBuildTime() string {
	if m != nil {
		return m.BuildTime
	}
	return ""
}

func (m *BlogDetailResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *BlogDetailResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func init() {
	proto.RegisterType((*BlogListRequest)(nil), "BlogListRequest")
	proto.RegisterType((*BlogListResponse)(nil), "BlogListResponse")
	proto.RegisterType((*BlogInfo)(nil), "BlogInfo")
	proto.RegisterType((*WriteBlogRequest)(nil), "WriteBlogRequest")
	proto.RegisterType((*WriteBlogResponse)(nil), "WriteBlogResponse")
	proto.RegisterType((*DeleteBlogRequest)(nil), "DeleteBlogRequest")
	proto.RegisterType((*DeleteBlogResponse)(nil), "DeleteBlogResponse")
	proto.RegisterType((*ModifyBlogRequest)(nil), "ModifyBlogRequest")
	proto.RegisterType((*ModifyBlogResponse)(nil), "ModifyBlogResponse")
	proto.RegisterType((*BlogDetailRequest)(nil), "BlogDetailRequest")
	proto.RegisterType((*BlogDetailResponse)(nil), "BlogDetailResponse")
}

func init() {
	proto.RegisterFile("go/src/rpc_blog/proto/blog/blog_ext.proto", fileDescriptor_a0c6db8a9d783a32)
}

var fileDescriptor_a0c6db8a9d783a32 = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0xed, 0xbf, 0x5f, 0x7f, 0xcd, 0xf4, 0x60, 0x33, 0x15, 0x09, 0xc1, 0x43, 0x59, 0x10, 0xaa,
	0xc2, 0x06, 0x6a, 0x41, 0x3c, 0x5a, 0x0a, 0x52, 0xd0, 0x4b, 0x14, 0xc4, 0x53, 0x69, 0x92, 0x6d,
	0x58, 0x48, 0xbb, 0x35, 0xd9, 0x88, 0x7e, 0x1f, 0x3f, 0xa8, 0xec, 0x36, 0x69, 0x42, 0x73, 0xb0,
	0x14, 0x2f, 0x61, 0x67, 0xf6, 0xcd, 0xbc, 0xd9, 0x37, 0x2f, 0x70, 0x19, 0x0a, 0x27, 0x89, 0x7d,
	0x27, 0xde, 0xf8, 0x73, 0x2f, 0x12, 0xa1, 0xb3, 0x89, 0x85, 0x14, 0x8e, 0x3e, 0xaa, 0xcf, 0x9c,
	0x7d, 0x4a, 0xaa, 0x73, 0xc4, 0x84, 0x93, 0x49, 0x24, 0xc2, 0x47, 0x9e, 0x48, 0x97, 0xbd, 0xa7,
	0x2c, 0x91, 0xe4, 0x0e, 0x7a, 0x45, 0x2a, 0xd9, 0x88, 0x75, 0xc2, 0xf0, 0x02, 0x3a, 0x5e, 0x96,
	0xb3, 0xea, 0x83, 0xe6, 0xb0, 0x3b, 0x32, 0xa8, 0x02, 0xcd, 0xd6, 0x4b, 0xe1, 0xee, 0xae, 0x88,
	0x0b, 0x9d, 0x3c, 0x8b, 0x08, 0xad, 0x34, 0xe5, 0x81, 0x55, 0x1f, 0xd4, 0x87, 0x86, 0xab, 0xcf,
	0x78, 0x0e, 0x86, 0x97, 0xf2, 0x28, 0x78, 0xe1, 0x2b, 0x66, 0x35, 0xf4, 0x45, 0x91, 0xc0, 0x53,
	0xf8, 0x27, 0xb9, 0x8c, 0x98, 0xd5, 0xd4, 0x37, 0xdb, 0x80, 0x5c, 0x41, 0xef, 0x35, 0xe6, 0x92,
	0xa9, 0xc6, 0xd9, 0x88, 0x78, 0x06, 0x6d, 0xc5, 0x39, 0xcb, 0xbb, 0x67, 0x11, 0xb9, 0x07, 0xb3,
	0x84, 0xcd, 0x66, 0x47, 0x68, 0xf9, 0x22, 0x60, 0x1a, 0xda, 0x74, 0xf5, 0x19, 0x2d, 0xf8, 0xbf,
	0x62, 0x49, 0xb2, 0x08, 0xf3, 0x31, 0xf2, 0x90, 0x5c, 0x83, 0x39, 0x65, 0x11, 0x3b, 0x8c, 0x6f,
	0x02, 0x58, 0x06, 0x1f, 0x45, 0xf8, 0x06, 0xe6, 0x93, 0x08, 0xf8, 0xf2, 0xeb, 0x00, 0xc2, 0x42,
	0xa2, 0x46, 0x49, 0x22, 0x85, 0x0e, 0x98, 0x5c, 0xf0, 0x28, 0x53, 0x2e, 0x8b, 0xd4, 0x78, 0xe5,
	0xd6, 0xc7, 0xea, 0xa1, 0xaa, 0xa7, 0xba, 0xe3, 0x6f, 0x7a, 0x48, 0xc0, 0x32, 0xb8, 0x20, 0xfc,
	0x0b, 0x27, 0x94, 0x9e, 0xd9, 0x2a, 0x3f, 0x73, 0xf4, 0xdd, 0x80, 0xae, 0xa2, 0x7d, 0x66, 0xf1,
	0x07, 0xf7, 0x19, 0x8e, 0xa1, 0xfb, 0xc0, 0x64, 0xee, 0x61, 0xec, 0xd1, 0x3d, 0x87, 0xdb, 0x26,
	0xdd, 0x37, 0x38, 0xa9, 0xe1, 0x18, 0x8c, 0x9d, 0x77, 0xd0, 0xa4, 0xfb, 0x9e, 0xb3, 0x91, 0x56,
	0xac, 0x45, 0x6a, 0x78, 0x0b, 0x50, 0x38, 0x00, 0x91, 0x56, 0xbc, 0x63, 0xf7, 0x69, 0xd5, 0x22,
	0xdb, 0xc2, 0x62, 0x37, 0x88, 0xb4, 0xe2, 0x01, 0xbb, 0x4f, 0xab, 0xcb, 0xdb, 0x16, 0x16, 0x1a,
	0x23, 0xd2, 0xca, 0x76, 0xec, 0x3e, 0xad, 0x2e, 0x81, 0xd4, 0xbc, 0xb6, 0xfe, 0xe3, 0x6f, 0x7e,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x61, 0x68, 0xa7, 0x1e, 0x04, 0x00, 0x00,
}
