// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: go/src/rpc_blog/proto/user/user_ext.proto

package user_ext

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserService interface {
	//注册用户
	RegisterUser(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterResponse, error)
	//登录用户
	LoginUser(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error)
	//退出登录
	LogOutUser(ctx context.Context, in *LogOutRequest, opts ...client.CallOption) (*LogOutResponse, error)
	//校验token
	VerifyToken(ctx context.Context, in *VerifyRequest, opts ...client.CallOption) (*VerifyResponse, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "userservice"
	}
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) RegisterUser(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.RegisterUser", in)
	out := new(RegisterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) LoginUser(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.LoginUser", in)
	out := new(LoginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) LogOutUser(ctx context.Context, in *LogOutRequest, opts ...client.CallOption) (*LogOutResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.LogOutUser", in)
	out := new(LogOutResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) VerifyToken(ctx context.Context, in *VerifyRequest, opts ...client.CallOption) (*VerifyResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.VerifyToken", in)
	out := new(VerifyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	//注册用户
	RegisterUser(context.Context, *RegisterRequest, *RegisterResponse) error
	//登录用户
	LoginUser(context.Context, *LoginRequest, *LoginResponse) error
	//退出登录
	LogOutUser(context.Context, *LogOutRequest, *LogOutResponse) error
	//校验token
	VerifyToken(context.Context, *VerifyRequest, *VerifyResponse) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		RegisterUser(ctx context.Context, in *RegisterRequest, out *RegisterResponse) error
		LoginUser(ctx context.Context, in *LoginRequest, out *LoginResponse) error
		LogOutUser(ctx context.Context, in *LogOutRequest, out *LogOutResponse) error
		VerifyToken(ctx context.Context, in *VerifyRequest, out *VerifyResponse) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) RegisterUser(ctx context.Context, in *RegisterRequest, out *RegisterResponse) error {
	return h.UserServiceHandler.RegisterUser(ctx, in, out)
}

func (h *userServiceHandler) LoginUser(ctx context.Context, in *LoginRequest, out *LoginResponse) error {
	return h.UserServiceHandler.LoginUser(ctx, in, out)
}

func (h *userServiceHandler) LogOutUser(ctx context.Context, in *LogOutRequest, out *LogOutResponse) error {
	return h.UserServiceHandler.LogOutUser(ctx, in, out)
}

func (h *userServiceHandler) VerifyToken(ctx context.Context, in *VerifyRequest, out *VerifyResponse) error {
	return h.UserServiceHandler.VerifyToken(ctx, in, out)
}
