// Code generated by protoc-gen-go. DO NOT EDIT.
// source: go/src/rpc_blog/proto/user/user_ext.proto

package user_ext

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0f430480574a4b0, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0f430480574a4b0, []int{1}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RegisterResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0f430480574a4b0, []int{2}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0f430480574a4b0, []int{3}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LoginResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type LogOutRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogOutRequest) Reset()         { *m = LogOutRequest{} }
func (m *LogOutRequest) String() string { return proto.CompactTextString(m) }
func (*LogOutRequest) ProtoMessage()    {}
func (*LogOutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0f430480574a4b0, []int{4}
}

func (m *LogOutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogOutRequest.Unmarshal(m, b)
}
func (m *LogOutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogOutRequest.Marshal(b, m, deterministic)
}
func (m *LogOutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogOutRequest.Merge(m, src)
}
func (m *LogOutRequest) XXX_Size() int {
	return xxx_messageInfo_LogOutRequest.Size(m)
}
func (m *LogOutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogOutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogOutRequest proto.InternalMessageInfo

type LogOutResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogOutResponse) Reset()         { *m = LogOutResponse{} }
func (m *LogOutResponse) String() string { return proto.CompactTextString(m) }
func (*LogOutResponse) ProtoMessage()    {}
func (*LogOutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0f430480574a4b0, []int{5}
}

func (m *LogOutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogOutResponse.Unmarshal(m, b)
}
func (m *LogOutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogOutResponse.Marshal(b, m, deterministic)
}
func (m *LogOutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogOutResponse.Merge(m, src)
}
func (m *LogOutResponse) XXX_Size() int {
	return xxx_messageInfo_LogOutResponse.Size(m)
}
func (m *LogOutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogOutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogOutResponse proto.InternalMessageInfo

func (m *LogOutResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LogOutResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "RegisterResponse")
	proto.RegisterType((*LoginRequest)(nil), "LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "LoginResponse")
	proto.RegisterType((*LogOutRequest)(nil), "LogOutRequest")
	proto.RegisterType((*LogOutResponse)(nil), "LogOutResponse")
}

func init() {
	proto.RegisterFile("go/src/rpc_blog/proto/user/user_ext.proto", fileDescriptor_d0f430480574a4b0)
}

var fileDescriptor_d0f430480574a4b0 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x4d, 0xda, 0xef, 0x53, 0x3b, 0xb6, 0x4d, 0x5d, 0x3c, 0x84, 0x9c, 0x64, 0x4f, 0x0a, 0xb2,
	0x01, 0xc5, 0xa3, 0xd2, 0x1f, 0x20, 0x08, 0x11, 0xcf, 0x21, 0x4d, 0x87, 0x10, 0x68, 0xb2, 0x71,
	0x67, 0xa3, 0xfe, 0x1f, 0xff, 0xa8, 0x64, 0xd2, 0x6d, 0x6d, 0x2e, 0x42, 0x2f, 0x21, 0x6f, 0xde,
	0xce, 0xcc, 0x7b, 0x6f, 0x17, 0x6e, 0x0a, 0x1d, 0x93, 0xc9, 0x63, 0xd3, 0xe4, 0xe9, 0x6a, 0xa3,
	0x8b, 0xb8, 0x31, 0xda, 0xea, 0xb8, 0x25, 0x34, 0xfc, 0x49, 0xf1, 0xcb, 0x2a, 0xae, 0xc9, 0x14,
	0x82, 0x04, 0x8b, 0x92, 0x2c, 0x9a, 0x04, 0xdf, 0x5b, 0x24, 0x2b, 0x2e, 0xe1, 0x3f, 0x56, 0x59,
	0xb9, 0x09, 0xfd, 0x2b, 0xff, 0x7a, 0x92, 0xf4, 0x40, 0x44, 0x70, 0xd6, 0xb5, 0xd6, 0x59, 0x85,
	0xe1, 0x88, 0x89, 0x1d, 0xee, 0xb8, 0x26, 0x23, 0xfa, 0xd4, 0x66, 0x1d, 0x8e, 0x7b, 0xce, 0x61,
	0xb9, 0x84, 0xc5, 0x7e, 0x01, 0x35, 0xba, 0x26, 0x14, 0x02, 0xfe, 0xe5, 0x7a, 0x8d, 0xbc, 0x60,
	0x9c, 0xf0, 0xbf, 0x08, 0xe1, 0xb4, 0x42, 0xa2, 0xac, 0x70, 0xe3, 0x1d, 0x94, 0x4b, 0x98, 0x3e,
	0xeb, 0xa2, 0xac, 0xff, 0xd4, 0xb7, 0xd3, 0x30, 0x1a, 0x68, 0x78, 0x84, 0xd9, 0x76, 0xc2, 0x51,
	0x02, 0x02, 0x6e, 0x7f, 0x69, 0xed, 0x56, 0x81, 0x7c, 0x82, 0xb9, 0x2b, 0x1c, 0x33, 0xf0, 0xee,
	0xdb, 0x87, 0xf3, 0x37, 0x42, 0xf3, 0x8a, 0xe6, 0xa3, 0xcc, 0x51, 0x3c, 0xc0, 0xd4, 0x65, 0xd4,
	0x95, 0xc5, 0x42, 0x0d, 0xee, 0x24, 0xba, 0x50, 0xc3, 0x10, 0xa5, 0x27, 0x6e, 0x61, 0xc2, 0xb6,
	0xb8, 0x67, 0xa6, 0x7e, 0x87, 0x14, 0xcd, 0xd5, 0x81, 0x63, 0xe9, 0x89, 0x18, 0xa0, 0x17, 0xcd,
	0xc7, 0x99, 0xdf, 0x5b, 0x8a, 0x02, 0x75, 0xe8, 0x48, 0x7a, 0xab, 0x13, 0x7e, 0x21, 0xf7, 0x3f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x24, 0x2b, 0x93, 0xf6, 0x4e, 0x02, 0x00, 0x00,
}
